const countryList = {
  AED: "AE",
  AFN: "AF",
  XCD: "AG",
  ALL: "AL",
  AMD: "AM",
  ANG: "AN",
  AOA: "AO",
  AQD: "AQ",
  ARS: "AR",
  AUD: "AU",
  AZN: "AZ",
  BAM: "BA",
  BBD: "BB",
  BDT: "BD",
  XOF: "BE",
  BGN: "BG",
  BHD: "BH",
  BIF: "BI",
  BMD: "BM",
  BND: "BN",
  BOB: "BO",
  BRL: "BR",
  BSD: "BS",
  NOK: "BV",
  BWP: "BW",
  BYR: "BY",
  BZD: "BZ",
  CAD: "CA",
  CDF: "CD",
  XAF: "CF",
  CHF: "CH",
  CLP: "CL",
  CNY: "CN",
  COP: "CO",
  CRC: "CR",
  CUP: "CU",
  CVE: "CV",
  CYP: "CY",
  CZK: "CZ",
  DJF: "DJ",
  DKK: "DK",
  DOP: "DO",
  DZD: "DZ",
  ECS: "EC",
  EEK: "EE",
  EGP: "EG",
  ETB: "ET",
  EUR: "FR",
  FJD: "FJ",
  FKP: "FK",
  GBP: "GB",
  GEL: "GE",
  GGP: "GG",
  GHS: "GH",
  GIP: "GI",
  GMD: "GM",
  GNF: "GN",
  GTQ: "GT",
  GYD: "GY",
  HKD: "HK",
  HNL: "HN",
  HRK: "HR",
  HTG: "HT",
  HUF: "HU",
  IDR: "ID",
  ILS: "IL",
  INR: "IN",
  IQD: "IQ",
  IRR: "IR",
  ISK: "IS",
  JMD: "JM",
  JOD: "JO",
  JPY: "JP",
  KES: "KE",
  KGS: "KG",
  KHR: "KH",
  KMF: "KM",
  KPW: "KP",
  KRW: "KR",
  KWD: "KW",
  KYD: "KY",
  KZT: "KZ",
  LAK: "LA",
  LBP: "LB",
  LKR: "LK",
  LRD: "LR",
  LSL: "LS",
  LTL: "LT",
  LVL: "LV",
  LYD: "LY",
  MAD: "MA",
  MDL: "MD",
  MGA: "MG",
  MKD: "MK",
  MMK: "MM",
  MNT: "MN",
  MOP: "MO",
  MRO: "MR",
  MTL: "MT",
  MUR: "MU",
  MVR: "MV",
  MWK: "MW",
  MXN: "MX",
  MYR: "MY",
  MZN: "MZ",
  NAD: "NA",
  XPF: "NC",
  NGN: "NG",
  NIO: "NI",
  NPR: "NP",
  NZD: "NZ",
  OMR: "OM",
  PAB: "PA",
  PEN: "PE",
  PGK: "PG",
  PHP: "PH",
  PKR: "PK",
  PLN: "PL",
  PYG: "PY",
  QAR: "QA",
  RON: "RO",
  RSD: "RS",
  RUB: "RU",
  RWF: "RW",
  SAR: "SA",
  SBD: "SB",
  SCR: "SC",
  SDG: "SD",
  SEK: "SE",
  SGD: "SG",
  SKK: "SK",
  SLL: "SL",
  SOS: "SO",
  SRD: "SR",
  STD: "ST",
  SVC: "SV",
  SYP: "SY",
  SZL: "SZ",
  THB: "TH",
  TJS: "TJ",
  TMT: "TM",
  TND: "TN",
  TOP: "TO",
  TRY: "TR",
  TTD: "TT",
  TWD: "TW",
  TZS: "TZ",
  UAH: "UA",
  UGX: "UG",
  USD: "US",
  UYU: "UY",
  UZS: "UZ",
  VEF: "VE",
  VND: "VN",
  VUV: "VU",
  YER: "YE",
  ZAR: "ZA",
  ZMK: "ZM",
  ZWD: "ZW",
};

const crrVal ={ 
  "USD":1,
  "AED":3.6725,
  "AFN":73.7466,
  "ALL":95.0594,
  "AMD":396.2400,
  "ANG":1.7900,
  "AOA":918.2652,
  "ARS":1060.8800,
  "AUD":1.5694,
  "AWG":1.7900,
  "AZN":1.6997,
  "BAM":1.8695,
  "BBD":2.0000,
  "BDT":121.5324,
  "BGN":1.8695,
  "BHD":0.3760,
  "BIF":2967.1131,
  "BMD":1.0000,
  "BND":1.3365,
  "BOB":6.9271,
  "BRL":5.7044,
  "BSD":1.0000,
  "BTN":86.6887,
  "BWP":13.8194,
  "BYN":3.2679,
  "BZD":2.0000,
  "CAD":1.4210,
  "CDF":2852.8049,
  "CHF":0.8984,
  "CLP":944.5455,
  "CNY":7.2553,
  "COP":4107.2829,
  "CRC":506.1269,
  "CUP":24.0000,
  "CVE":105.3979,
  "CZK":23.9450,
  "DJF":177.7210,
  "DKK":7.1298,
  "DOP":62.2226,
  "DZD":135.0324,
  "EGP":50.5749,
  "ERN":15.0000,
  "ETB":126.7471,
  "EUR":0.9559,
  "FJD":2.2965,
  "FKP":0.7912,
  "FOK":7.1298,
  "GBP":0.7912,
  "GEL":2.8090,
  "GGP":0.7912,
  "GHS":15.5129,
  "GIP":0.7912,
  "GMD":72.5964,
  "GNF":8631.1970,
  "GTQ":7.7194,
  "GYD":209.5452,
  "HKD":7.7715,
  "HNL":25.5719,
  "HRK":7.2019,
  "HTG":131.1804,
  "HUF":385.5947,
  "IDR":16310.6676,
  "ILS":3.5671,
  "IMP":0.7912,
  "INR":86.6888,
  "IQD":1309.6520,
  "IRR":41999.1083,
  "ISK":139.2712,
  "JEP":0.7912,
  "JMD":157.5204,
  "JOD":0.7090,
  "JPY":149.5493,
  "KES":129.5489,
  "KGS":87.4212,
  "KHR":4013.7756,
  "KID":1.5694,
  "KMF":470.2523,
  "KRW":1434.5816,
  "KWD":0.3087,
  "KYD":0.8333,
  "KZT":504.1718,
  "LAK":21903.3618,
  "LBP":89500.0000,
  "LKR":295.9554,
  "LRD":199.4573,
  "LSL":18.3534,
  "LYD":4.8947,
  "MAD":9.9615,
  "MDL":18.6775,
  "MGA":4738.4704,
  "MKD":58.8038,
  "MMK":2100.3279,
  "MNT":3495.5822,
  "MOP":8.0046,
  "MRU":39.9518,
  "MUR":46.4319,
  "MVR":15.4627,
  "MWK":1744.7413,
  "MXN":20.3789,
  "MYR":4.4209,
  "MZN":63.9974,
  "NAD":18.3534,
  "NGN":1503.4422,
  "NIO":36.8130,
  "NOK":11.1264,
  "NPR":138.7019,
  "NZD":1.7402,
  "OMR":0.3845,
  "PAB":1.0000,
  "PEN":3.6891,
  "PGK":4.0242,
  "PHP":57.9196,
  "PKR":279.4252,
  "PLN":3.9774,
  "PYG":7909.3943,
  "QAR":3.6400,
  "RON":4.7558,
  "RSD":112.1137,
  "RUB":88.7882,
  "RWF":1434.8051,
  "SAR":3.7500,
  "SBD":8.6570,
  "SCR":14.3984,
  "SDG":509.4217,
  "SEK":10.6454,
  "SGD":1.3365,
  "SHP":0.7912,
  "SLE":22.8566,
  "SLL":22856.6481,
  "SOS":571.9307,
  "SRD":35.5989,
  "SSP":4406.7040,
  "STN":23.4186,
  "SYP":12943.6598,
  "SZL":18.3534,
  "THB":33.5893,
  "TJS":10.9249,
  "TMT":3.5005,
  "TND":3.1663,
  "TOP":2.3840,
  "TRY":36.4616,
  "TTD":6.7078,
  "TVD":1.5694,
  "TWD":32.7461,
  "TZS":2584.8943,
  "UAH":41.5808,
  "UGX":3674.0723,
  "UYU":43.2420,
  "UZS":12937.4828,
  "VES":63.4139,
  "VND":25515.9258,
  "VUV":123.1087,
  "WST":2.8101,
  "XAF":627.0030,
  "XCD":2.7000,
  "XDR":0.7614,
  "XOF":627.0030,
  "XPF":114.0647,
  "YER":247.6860,
  "ZAR":18.3534,
  "ZMW":28.2344,
  "ZWL":26.4642
}
  
  const fullCountryName={
      "Afghanistan": "AF",
      "Albania": "AL",
      "Algeria": "DZ",
      "Andorra": "AD",
      "Angola": "AO",
      "Antigua and Barbuda": "AG",
      "Argentina": "AR",
      "Armenia": "AM",
      "Australia": "AU",
      "Austria": "AT",
      "Azerbaijan": "AZ",
      "Bahamas": "BS",
      "Bahrain": "BH",
      "Bangladesh": "BD",
      "Barbados": "BB",
      "Belarus": "BY",
      "Belgium": "BE",
      "Belize": "BZ",
      "Benin": "BJ",
      "Bhutan": "BT",
      "Bolivia": "BO",
      "Bosnia and Herzegovina": "BA",
      "Botswana": "BW",
      "Brazil": "BR",
      "Brunei": "BN",
      "Bulgaria": "BG",
      "Burkina Faso": "BF",
      "Burundi": "BI",
      "Cabo Verde": "CV",
      "Cambodia": "KH",
      "Cameroon": "CM",
      "Canada": "CA",
      "Central African Republic": "CF",
      "Chad": "TD",
      "Chile": "CL",
      "China": "CN",
      "Colombia": "CO",
      "Comoros": "KM",
      "Congo (Congo-Brazzaville)": "CG",
      "Costa Rica": "CR",
      "Croatia": "HR",
      "Cuba": "CU",
      "Cyprus": "CY",
      "Czechia (Czech Republic)": "CZ",
      "Democratic Republic of the Congo": "CD",
      "Denmark": "DK",
      "Djibouti": "DJ",
      "Dominica": "DM",
      "Dominican Republic": "DO",
      "Ecuador": "EC",
      "Egypt": "EG",
      "El Salvador": "SV",
      "Equatorial Guinea": "GQ",
      "Eritrea": "ER",
      "Estonia": "EE",
      "Eswatini": "SZ",
      "Ethiopia": "ET",
      "Fiji": "FJ",
      "Finland": "FI",
      "France": "FR",
      "Gabon": "GA",
      "Gambia": "GM",
      "Georgia": "GE",
      "Germany": "DE",
      "Ghana": "GH",
      "Greece": "GR",
      "Grenada": "GD",
      "Guatemala": "GT",
      "Guinea": "GN",
      "Guinea-Bissau": "GW",
      "Guyana": "GY",
      "Haiti": "HT",
      "Honduras": "HN",
      "Hungary": "HU",
      "Iceland": "IS",
      "India": "IN",
      "Indonesia": "ID",
      "Iran": "IR",
      "Iraq": "IQ",
      "Ireland": "IE",
      "Israel": "IL",
      "Italy": "IT",
      "Jamaica": "JM",
      "Japan": "JP",
      "Jordan": "JO",
      "Kazakhstan": "KZ",
      "Kenya": "KE",
      "Kiribati": "KI",
      "Kuwait": "KW",
      "Kyrgyzstan": "KG",
      "Laos": "LA",
      "Latvia": "LV",
      "Lebanon": "LB",
      "Lesotho": "LS",
      "Liberia": "LR",
      "Libya": "LY",
      "Liechtenstein": "LI",
      "Lithuania": "LT",
      "Luxembourg": "LU",
      "Madagascar": "MG",
      "Malawi": "MW",
      "Malaysia": "MY",
      "Maldives": "MV",
      "Mali": "ML",
      "Malta": "MT",
      "Marshall Islands": "MH",
      "Mauritania": "MR",
      "Mauritius": "MU",
      "Mexico": "MX",
      "Micronesia": "FM",
      "Moldova": "MD",
      "Monaco": "MC",
      "Mongolia": "MN",
      "Montenegro": "ME",
      "Morocco": "MA",
      "Mozambique": "MZ",
      "Myanmar (Burma)": "MM",
      "Namibia": "NA",
      "Nauru": "NR",
      "Nepal": "NP",
      "Netherlands": "NL",
      "New Zealand": "NZ",
      "Nicaragua": "NI",
      "Niger": "NE",
      "Nigeria": "NG",
      "North Korea": "KP",
      "North Macedonia": "MK",
      "Norway": "NO",
      "Oman": "OM",
      "Pakistan": "PK",
      "Palau": "PW",
      "Palestine State": "PS",
      "Panama": "PA",
      "Papua New Guinea": "PG",
      "Paraguay": "PY",
      "Peru": "PE",
      "Philippines": "PH",
      "Poland": "PL",
      "Portugal": "PT",
      "Qatar": "QA",
      "Romania": "RO",
      "Russia": "RU",
      "Rwanda": "RW",
      "Saint Kitts and Nevis": "KN",
      "Saint Lucia": "LC",
      "Saint Vincent and the Grenadines": "VC",
      "Samoa": "WS",
      "San Marino": "SM",
      "Sao Tome and Principe": "ST",
      "Saudi Arabia": "SA",
      "Senegal": "SN",
      "Serbia": "RS",
      "Seychelles": "SC",
      "Sierra Leone": "SL",
      "Singapore": "SG",
      "Slovakia": "SK",
      "Slovenia": "SI",
      "Solomon Islands": "SB",
      "Somalia": "SO",
      "South Africa": "ZA",
      "South Korea": "KR",
      "South Sudan": "SS",
      "Spain": "ES",
      "Sri Lanka": "LK",
      "Sudan": "SD",
      "Suriname": "SR",
      "Sweden": "SE",
      "Switzerland": "CH",
      "Syria": "SY",
      "Taiwan": "TW",
      "Tajikistan": "TJ",
      "Tanzania": "TZ",
      "Thailand": "TH",
      "Timor-Leste": "TL",
      "Togo": "TG",
      "Tonga": "TO",
      "Trinidad and Tobago": "TT",
      "Tunisia": "TN",
      "Turkey": "TR",
      "Turkmenistan": "TM",
      "Tuvalu": "TV",
      "Uganda": "UG",
      "Ukraine": "UA",
      "United Arab Emirates": "AE",
      "United Kingdom": "GB",
      "United States of America": "US",
      "Uruguay": "UY",
      "Uzbekistan": "UZ",
      "Vanuatu": "VU",
      "Vatican City": "VA",
      "Venezuela": "VE",
      "Vietnam": "VN",
      "Yemen": "YE",
      "Zambia": "ZM",
      "Zimbabwe": "ZW"
    };
    
  
  const languages = {
    en: 'English',
    es: 'Spanish',
    fr: 'French',
    de: 'German',
    zh: 'Chinese',
    ja: 'Japanese',
    hi: 'Hindi',
    // Add more languages as needed
  };
  export default{
    languages,
    countryList,
    crrVal,
    fullCountryName,

  }
 